services:
  # jupyter:  # you can change this to whatever you want.
  #   container_name: machine-learning-workspace
  #   image: tensorflow/tensorflow:2.17.0-gpu-jupyter
  #   volumes:
  #     - "./:/tf/notebooks"
  #   ports:
  #    - "8888:8888"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         -  driver: nvidia
  #            count: all
  #            capabilities: [gpu]
  jupyter-2:  # you can change this to whatever you want.
    container_name: machine-learning-workspace-2
    image: tensorflow/tensorflow:2.18.0-gpu-jupyter
    volumes:
      - "./:/tf/notebooks"
    ports:
     - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]